version: '3.8'

services:
  train:
    build:
      context: .
    command: |
      python -m src.train
    volumes:
      - data:/app/data
      - checkpoints:/app/checkpoints
      - artifacts:/app/artifacts
      - logs:/app/logs
    shm_size: '4g' 
    networks:
      - default
    env_file:
      - .env 

  eval:
    build:
      context: .
    command: |
      /bin/bash -c "while [ ! -f /checkpoints/train_done.flag ]; do sleep 10; done;
      python -m src.eval"
    volumes:
      - data:/app/data
      - checkpoints:/app/checkpoints
      - artifacts:/app/artifacts
      - logs:/app/logs
    shm_size: '4g'
    networks:
      - default
    depends_on:
      - train
    env_file:
      - .env  

  inference:
    build:
      context: .
    command: |
      /bin/bash -c "while [ ! -f /checkpoints/train_done.flag ]; do sleep 10; done;
      python -m src.infer"
    volumes:
      - data:/app/data
      - checkpoints:/app/checkpoints
      - artifacts:/app/artifacts
      - logs:/app/logs
    shm_size: '4g'
    networks:
      - default
    depends_on:
      - train
    env_file:
      - .env  

volumes:
  data:
  checkpoints:
  artifacts:
  logs:

networks:
  default:
