# @package _global_

defaults:
  - override /hydra/sweeper: optuna

# We want to optimize for the highest test accuracy
optimization_metric: "test_acc_best"

hydra:
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 123
      n_startup_trials: 3
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    # Define the attrbs of the optimization
    direction: maximize
    study_name: catdog_hparam_optimization
    storage: null
    n_trials: 5
    n_jobs: 1
    # Define the hyperparameters to optimize
    params:
      model.lr: interval(1e-5, 1e-3)
      model.weight_decay: interval(1e-6, 1e-4)
      
