name: CI Pipeline

on:
  push:
    branches:
      - main
      - feat/*
  pull_request:
    branches:
      - main
      - feat/*

jobs:
  test:
    name: Test on Python code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10.14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('pytorch_project/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        working-directory: pytorch_project  # Install dependencies inside pytorch_project
        run: |
          poetry install

      # **Run tests in the root directory (where the tests folder is located)**
      - name: Run tests with verbose output
        run: |
          poetry run pytest -v

      # **Run lint check at the root level**
      - name: Run lint checks
        run: |
          poetry run flake8 .

      # **Check Poetry environment at the root level**
      - name: Check Poetry environment
        run: |
          poetry env info
